### ISSUE TITLE
Merge favorites models and serializers

### ISSUE THREAD

**Issue by BrunaNayara** [AcompanhaLegis/acompanha-legis-api#5]
# Problem
Currently, there is two models `FavoriteProposicao` and `FavoriteDeputado`. They are not very different. 

# Solution
The gerenal solution is to make them as choices. Like they are in the updates app.
Attributes: `name-year` and `name-partido` for the new model.
 See examples: 
- [updates model] 
- [updates serializer]

## Tasks
- [ ] Change favorites models
- [ ] Change favorites serializers
- [ ] Update any calls fo the models/serializers

[updates model]: https://github.com/AcompanhaLegis/acompanha-legis-api/blob/master/api/updates/models.py
[updates serializer]: https://github.com/AcompanhaLegis/acompanha-legis-api/blob/master/api/updates/serializers.py

**Comment by Joranhezon** [comment]
Hi! I would like to work on this one. :)

The solution would be to update these attributes with parameters `blank` and `null` as `True`?

**Comment by Joranhezon** [comment]
Actually, since `null` willl already be set as `True`, perhaps we don't need the `blank` parameter anymore?
