### ISSUE TITLE
Remove twitter of the metrics model 

### ISSUE THREAD

**Issue by BrunaNayara** [AcompanhaLegis/acompanha-legis-api#8]
# Problem
There is an attribute (twitter) that is requested directly from the other API used in the front end. There is no need for it here. 

# Solution
Remove the [attribute from the model](https://github.com/AcompanhaLegis/acompanha-legis-api/blob/master/api/metrics/models.py#L8) and any other appropriate place.

## Tasks
- [ ] Remove it from model
- [ ] Look for other places to remove it
- [ ] Create the related migration

**Comment by ashvinimore** [comment]
Hello Bruna,
Do you want to remove field twitter from models. Modify migrations files  and migrate the model. So,It won't  get displayed in frontend ?
Thank You

**Comment by BrunaNayara** [comment]
@ashvinimore Yep! That is correct. 
I'll add the migration file as a task in the description.
